### PR TITLE
Ensembl mirror argument added

### PR DESCRIPTION
**Pull request by zuzkamat**
I have repeatedly encountered a connection error while using biomaRt::useEnsembl() function. It might be the case also for other users based in Central Europe like me. This issue can be solved by specifying "mirror" argument within the function (in my case "useast" was the option that worked). 
However, this function is also embeded deep in gruffi::GO_score_evaluation() function, which failed as "mirror" could not be easily specified. Therefore, I have added "mirror" as optional argument into GO_score_evaluation(), PlotGoTermScores(), and GetGOTerms() functions. 
See the Traceback of the error below (step number 1 is my custom function covering the whole Gruffi pipeline based on the original vignette):

```r
Error in bmRequest(request = request, httr_config = httr_config, verbose = verbose) :
Not Found (HTTP 404).
12.
stop(http_condition(x, "error", task = task, call = call))
11.
stop_for_status(result)
10.
bmRequest(request = request, httr_config = httr_config, verbose = verbose)
9.
.listDatasets(mart, sort = FALSE)
8.
checkDataset(dataset = dataset, mart = mart)
7.
useDataset(mart = mart, dataset = dataset, verbose = verbose)
6.
.useMart(biomart = biomart, dataset = dataset, host = host, verbose = verbose,
port = port, ensemblRedirect = ensemblRedirect, httr_config = httr_config)
5.
biomaRt::useEnsembl("ensembl", dataset = "hsapiens_gene_ensembl",
version = version, GRCh = GRCh)
4.
GetGOTerms(obj = obj, GO = GO, web.open = openBrowser, use.ensemble = use.ensemble)
3.
PlotGoTermScores(GO = GO_term, save.UMAP = save.UMAP, obj = obj,
desc = description, plot.each.gene = plot.each.gene)
2.
GO_score_evaluation(obj = seurat_object_gruffi, GO_term = go1,
save.UMAP = TRUE, new_GO_term_computation = T, clustering = granule.res.4.gruffi,
plot.each.gene = F) at gruffi_organoids.R#44
1.
Gruffi_stressed(seurat_object, assay = "RNA", organism = "hsapiens_gene_ensembl",
negative_GOterm = "GO:0022008")
```

### CODE REVIEW

**Comment by vertesy** [comment]
Hello, and very sorry for not being able to address this before. I appreciate your input, I was just too busy.
Yes, I agree with this being a problem and will review the code now. Thank you! 

Of note, I did a major update of the package (bf, cleanup) so probably I will implement manually based on your code.

**Comment by vertesy** [comment]
Ok, since its easy to miss changed in manual implementation, do I get it correcly that there were only 2 function changes?

1. `GetGOTerms()`
2. `GO_score_evaluation() `?

### Changes in `GetGOTerms()`
```r
#' @param mirror Which Ensembl mirror to use in biomaRt::useEnsembl()? If connection to Ensembl fails with default settings, mirror can be specified. Default: 'NULL'
```
and
```r
mirror = NULL,
```
and
```r
ensembl <<- biomaRt::useEnsembl("ensembl", dataset = "hsapiens_gene_ensembl", version = version, GRCh = GRCh, mirror = mirror)
```

### Changes in `GO_score_evaluation()`
```r
#' @param mirror Which Ensembl mirror to use in biomaRt::useEnsembl()? If connection to Ensembl fails with default settings, mirror can be specified. Default: 'NULL'
```
and
```r
mirror = NULL,
```
and
```r
    obj <- PlotGoTermScores(
      GO = GO_term, save.UMAP = save.UMAP, obj = obj,
      desc = description, plot.each.gene = plot.each.gene, mirror = mirror
    )
```

**Comment by vertesy** [comment]
Not yet tested, but will close it now.

**Comment by vertesy** [comment]
Thank you for the implementation!

**Comment by zuzkamat** [comment]
Hey vertesy, thanks for your feedback! Apologies for any imperfections in my pull request, it was the first one ever for me. :)

**Comment by vertesy** [comment]
It wasn't your fault:  the code changed too much in recent updates and merge would have been messy -  I should have merged before, but well. Thanks again!

**Pull request closed without merging**
